#!/usr/bin/env python3
"""Generate SWAG nginx configuration snippets from environment variables.

Replaces the former Traefik middlewares.yml generator. The project migrated
from Traefik (dynamic YAML + docker labels) to SWAG (LinuxServer nginx +
certbot). Rather than a standalone middleware file, SWAG uses static nginx
proxy-conf files that ``include`` reusable snippet files.

This script emits two snippet files into ``swag/proxy-confs/``:

* ``_cors_headers.conf``   — ``add_header`` directives driven by
  ``MCP_CORS_ORIGINS`` (mirrors the old CORS middleware config).
* ``_oauth_verify.conf``   — the internal ``/_oauth_verify`` location block
  used by ``auth_request`` in every MCP proxy-conf.

Both files are prefixed with ``_`` so SWAG does not load them as standalone
virtual-host configs (SWAG only auto-includes ``*.conf`` files that declare a
``server {}`` block, but the underscore prefix makes intent explicit).
"""

import os
import sys
from pathlib import Path


def generate_cors_origins(origins_str: str) -> tuple[list[str], bool]:
    """Parse the MCP_CORS_ORIGINS env var into a list and credentials flag.

    Args:
        origins_str: Comma-separated CORS origin URLs, ``*`` for wildcard,
            or empty string to fall back to ``http://localhost``.

    Returns:
        Tuple of (origins list, allow_credentials flag).

    """
    if not origins_str or not origins_str.strip():
        return ["http://localhost"], False

    if origins_str.strip() == "*":
        return ["*"], False

    origins = [o.strip() for o in origins_str.split(",") if o.strip()]
    if not origins:
        return ["http://localhost"], False

    return origins, True


def build_cors_snippet(origins: list[str], allow_credentials: bool) -> str:
    """Render the nginx ``add_header`` CORS snippet.

    Args:
        origins: List of allowed origin strings.
        allow_credentials: Whether ``Access-Control-Allow-Credentials`` is
            ``true`` (must be ``false`` when origin is ``*``).

    Returns:
        nginx snippet as a string (no surrounding ``server {}`` block).

    """
    creds = "true" if allow_credentials else "false"

    if len(origins) == 1 and origins[0] == "*":
        origin_value = '"*"'
    else:
        # nginx cannot set a dynamic list of origins natively; emit a map
        # variable assignment pattern instead using the first origin as the
        # static fallback, documented clearly for operators.
        origin_value = "$http_origin"

    lines = [
        "# CORS headers snippet — generated by scripts/generate_middlewares.py",
        "# Include this file inside an authenticated location block.",
        "#",
        "# Allowed origins (from MCP_CORS_ORIGINS):",
        *[f"#   {o}" for o in origins],
        "",
    ]

    if len(origins) > 1:
        # Emit a geo/map block comment explaining that a map is needed in the
        # http context; operators must add it to nginx.conf manually.  Here we
        # only emit the add_header directives which reference $cors_origin,
        # a variable the proxy-conf template sets via the inline origin-valid
        # check already present in mcp-template.subdomain.conf.
        lines += [
            "# NOTE: Multiple origins detected. The mcp-template.subdomain.conf",
            "# already validates $http_origin against allowed values and sets",
            "# $origin_valid. The add_header directives below reflect $http_origin",
            "# directly — nginx will echo back the validated request origin.",
            "",
        ]

    lines += [
        f'add_header Access-Control-Allow-Origin {origin_value} always;',
        'add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, DELETE" always;',
        'add_header Access-Control-Allow-Headers '
        '"Authorization, Content-Type, Accept, '
        'MCP-Protocol-Version, Mcp-Session-Id, Last-Event-ID" always;',
        f'add_header Access-Control-Allow-Credentials "{creds}" always;',
        'add_header Access-Control-Max-Age "3600" always;',
    ]

    return "\n".join(lines) + "\n"


def build_oauth_verify_snippet(auth_service_host: str) -> str:
    """Render the nginx internal ``/_oauth_verify`` location snippet.

    This location is referenced by ``auth_request /_oauth_verify;`` inside
    every MCP endpoint location block.  It forwards the request to the auth
    service ``/verify`` endpoint without passing the request body.

    Args:
        auth_service_host: Docker service hostname for the auth service
            (defaults to ``mcp-oauth``).

    Returns:
        nginx location block as a string.

    """
    return f"""\
# OAuth 2.1 token verification snippet — generated by scripts/generate_middlewares.py
# Include this file inside a server {{}} block (outside any location block).
# Usage in a location that requires auth:
#
#   auth_request /_oauth_verify;
#   auth_request_set $auth_status $upstream_status;
#
location = /_oauth_verify {{
    internal;
    include /config/nginx/resolver.conf;
    proxy_pass http://{auth_service_host}:8000/verify;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
    proxy_set_header X-Original-Method $request_method;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Authorization $http_authorization;
}}
"""


def main() -> None:
    """Generate SWAG nginx snippet files and write them to swag/proxy-confs/."""
    cors_origins_str = os.getenv("MCP_CORS_ORIGINS", "")
    base_domain = os.getenv("BASE_DOMAIN", "localhost")
    auth_service_host = os.getenv("AUTH_SERVICE_HOST", "mcp-oauth")

    repo_root = Path(__file__).parent.parent
    output_dir = repo_root / "swag" / "proxy-confs"

    output_dir.mkdir(parents=True, exist_ok=True)

    # --- CORS snippet ---
    origins, allow_credentials = generate_cors_origins(cors_origins_str)
    cors_content = build_cors_snippet(origins, allow_credentials)
    cors_path = output_dir / "_cors_headers.conf"
    cors_path.write_text(cors_content)
    print(f"Generated {cors_path}")

    # --- OAuth verify snippet ---
    verify_content = build_oauth_verify_snippet(auth_service_host)
    verify_path = output_dir / "_oauth_verify.conf"
    verify_path.write_text(verify_content)
    print(f"Generated {verify_path}")

    # --- Summary ---
    print(f"CORS Origins   : {cors_origins_str or 'none (fallback: http://localhost)'}")
    print(f"Allow Credentials: {allow_credentials}")
    print(f"Base Domain    : {base_domain}")
    print(f"Auth Service   : {auth_service_host}:8000")


if __name__ == "__main__":
    main()
